### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#100]
Dumping some thoughts here for improvements to the docs.

### Design system info

Describe how to use each component in the context of a design system. Think dos/dont's and basic usage guidelines.

### Component anatomy (CSS Parts)

Many folks seem to have trouble with CSS parts. We currently dump all the text info into a table. I'm thinking we should probably add illustrations to more clearly define the parts of each element.

### Supported Content for Slots

It's not very clear what type of content is supported in slots. We've been relying on users to infer what belongs there from context and examples, which leads to issues like shoelace-style/shoelace#1697 where interactive content is placed where it shouldn't be. This isn't the fault of users, since we don't bother to document what can exist where.

Instead of throwing more text at users, I think we can identify and group types of content (e.g. interactive, non-interactive) and use something like the checkmarks used in the _Reflects_ column of properties. For more info, those could link to a page that clearly defines what each content group means.

MDN does something similar with [content categories](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories) and documents them under "permitted content." Perhaps we can use this for inspiration.

**Comment by mariohamann** [comment]
Some inspiration from a project I'm working on:

![CleanShot 2023-11-22 at 09 54 56](https://github.com/shoelace-style/shoelace/assets/26542182/852c1db4-5700-49c3-b1c7-adbd6e9e16b4)

https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-input--parts

We're providing an overview of all parts we use.

I think you could do this even interactively. Here an example with tabs:

https://github.com/shoelace-style/shoelace/assets/26542182/3e249357-d883-4539-9b90-fb0c56603109

https://codepen.io/mariohamann/pen/oNmdvOy?editors=1000

**Comment by claviska** [comment]
That interactive example is an awesome idea! I think we can make something like that work.
