### ISSUE TITLE
Custom Property Additions for 3.0

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#14]
This issue cover CSS custom properties that we'll be adding to individual components _on top of_ the global, `--wa-` prefixed design tokens we already offer. Previously, we used CSS parts sparingly. Now we want to solve 90% of style customizations with custom properties and reserve parts for advanced cases.

## Components to audit

- [x] alert
- [x] animated-image
- [x] animation
- [x] avatar
- [x] badge
- [x] breadcrumb
- [x] breadcrumb-item
- [x] button
- [x] button-group
- [x] card
- [x] carousel
- [x] carousel-item
- [x] checkbox
- [x] color-picker
- [x] copy-button
- [x] details
- [x] dialog
- [x] divider
- [x] drawer
- [x] dropdown
- [x] format-bytes
- [x] format-date
- [x] format-number
- [x] icon
- [x] icon-button
- [x] image-comparer
- [x] include
- [x] input
- [ ] layout
- [x] menu
- [x] menu-item
- [x] menu-label
- [x] mutation-observer
- [x] option
- [x] popup
- [x] progress-bar
- [x] progress-ring
- [x] qr-code
- [x] radio
- [x] radio-button
- [x] radio-group
- [x] range
- [x] rating
- [x] relative-time
- [x] resize-observer
- [x] select
- [x] skeleton
- [x] spinner
- [x] split-panel
- [x] switch
- [x] tab
- [x] tab-group
- [x] tab-panel
- [x] tag
- [x] textarea
- [x] tooltip
- [x] tree
- [x] tree-item
- [x] visually-hidden

**Comment by lindsaym-fa** [comment]
For reference and discussion, these are the rules I've been following so far when adding component-scoped custom properties:

- Expose anything that's a distinguishing characteristic of the component, e.g. a button's background and label color or an input's border styles
- Prefer shorthand properties that offer flexibility without getting too granular
  - Example 1: Prefer `background` over `background-color` to support `linear-gradient()` or other image-type values
  - Example 2: Prefer `border-color`, `border-style`, and `border-width` over the more general shorthand `border` to support distinct values for all sides; also prefer over more specific properties like `border-top-width`, `border-bottom-color`, etc. to avoid unnecessarily complicated customization
- Expose common color properties for expected states, like `border-color`, `border-color-active`, `border-color-hover`, `border-color-checked`, etc. This ensures that customizing the default/resting color won't unexpectedly override the color for all states.
- Expose properties that should remain the same for all variants with `:host`; expose properties that change per attribute with `:host([attribute])`

**Comment by lindsaym-fa** [comment]
These have been addressed in PR #126 with the exception of `<wa-page>`, which isn't included in the WA Free alpha. Issue #127 has been created for that final audit.
