### ISSUE TITLE
Important Proposals for Web Awesome

### ISSUE THREAD

**Issue by KonnorRogers** [shoelace-style/webawesome#150]
## Platform Proposals

- Current Language: <https://github.com/whatwg/html/issues/7039>
- Slot Detection: <https://github.com/w3c/csswg-drafts/issues/6867>
- Template instantiation: <https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md>
- Declarative custom elements: <https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Declarative-Custom-Elements-Strawman.md>

## ElementInternals

- Allow a custom element to be a submit button <https://github.com/WICG/webcomponents/issues/814>
- Allow a custom element to be a form <https://github.com/whatwg/html/issues/10220>

### Cross Root Aria

- <https://github.com/leobalter/cross-root-aria-delegation/blob/main/explainer.md>
-  <https://github.com/WICG/aom/issues/169>
- <https://github.com/WICG/aom/issues/107>
- <https://github.com/WICG/webcomponents/issues/917>
- <https://github.com/WICG/webcomponents/issues/916>

**Comment by LeaVerou** [comment]
Thank you so much for this @KonnorRogers, it was immensely helpful in preparing for TPAC. I've started this doc before TPAC where we could manage this in a more structured way: https://coda.io/d/Web-Platform-Pain-Points-WIP_dzVjS43KNGK/Web-Platform-Pain-Points_suAb5Tqp
