### ISSUE TITLE
Bring back resizable code examples

### ISSUE THREAD

**Issue by lindsaym-fa** [shoelace-style/webawesome#167]
Our code examples would benefit from being resizable to highlight each component's responsiveness, and the [`wa-resize-observer`](https://backers.webawesome.com/docs/components/resize-observer) example explicitly relies on it. Let's bring back the resizable code examples we enjoyed with Shoelace. 😊

**Comment by claviska** [comment]
That's fair. Would it be better to use preset buttons for mobile/tablet/desktop or do you want it to behave the same as before?

**Comment by lindsaym-fa** [comment]
Free resizing has my vote. The flexibility would better satisfy folk's curiosity, I think.

**Comment by LeaVerou** [comment]
@lindsaym-fa do you think this should be an opt-in or an opt-out?

**Comment by lindsaym-fa** [comment]
I'd argue for opt-out. I feel like I see this feature on code examples more often than not.

**Comment by LeaVerou** [comment]
Agreed — that’s how I've implemented it so far. In fact, the opt-out is not yet implemented 😁

**Comment by LeaVerou** [comment]
Closed via #281
