### ISSUE TITLE
issues to backport

### ISSUE THREAD

**Issue by KonnorRogers** [shoelace-style/webawesome#183]
- [ ] - https://github.com/shoelace-style/shoelace/pull/2198
- [ ] - https://github.com/shoelace-style/shoelace/pull/2182
- [ ] - https://github.com/shoelace-style/shoelace/pull/2197
- [ ] - https://github.com/shoelace-style/shoelace/pull/2211
- [ ] - https://github.com/shoelace-style/shoelace/pull/2210
- [ ] - https://github.com/shoelace-style/shoelace/pull/2189
- [ ] - https://github.com/shoelace-style/shoelace/pull/2192
- [ ] - https://github.com/shoelace-style/shoelace/pull/2218

**Comment by claviska** [comment]
Closing. Added these to #61.
