### ISSUE TITLE
The WA autoloader swallows errors (sometimes)

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#199]
After #196, I added `data-webawesome` with a relative path (`foo/bar`) which presumably is not the way to go. However, I was not notified about the error of my ways; instead all I got was a completely blank page (see #198) and no console errors, so I was left scratching my head as to what happened.

It was only after I inserted debugging statements in to the WA codebase that I was able to figure it out: some of the promises in `discover()` had gotten rejected. The error wasn't particularly clear either: 

```
Error: Unable to autoload <wa-page> from foo/bar/components/page/page.js
    at http://localhost:8002/foo/bar/wa/chunks/chunk.XTO37P3H.js:33:59"
```

The line number it references is just the one composing this generic error: https://github.com/shoelace-style/webawesome/blob/next/src/utilities/autoloader.ts#L48

That said, while a more specific error would have been more helpful, even printing the generic one out as a warning would have been a better experience. Even though I wouldn't know _what_ was wrong, I would at least know that _something_ went wrong.

Perhaps something like this:

```js
let imports = await Promise.allSettled(tagsToRegister.map((tagName) => register(tagName)));
  for (let r of imports) {
    if (r.status === "rejected") {
      console.warn(r.reason);
    }
  }
```

Though not sure why `register()` needs to `catch()` anyway: since you’re using `Promise.allSettled()`, shouldn't that take care of it? If it's just for a more readable error, you can pass the original error via the [`cause` constructor option](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#cause). 
(When I tried that, I discovered what the real reason was: "TypeError: Failed to resolve module specifier 'foo/bar/components/page/page.js'"...)

**Comment by claviska** [comment]
PRs fine for this — we can also probably link to the docs from the error content :)
