### ISSUE TITLE
Relative URLs in `data-webawesome` behave unpredictably

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#200]
After realizing I needed to use a `data-webawesome` attribute (see #196), my first attempt was to use a relative URL (see #198 #199). After a lot of trial and error, I realized what the relative URLs were relative _to_: `chunks/chunk.XTO37P3H.js` that was doing the fetching! 

`data-webawesome=".."` eventually worked, but it was _very_ nonobvious. This means authors need to understand the internal WA structure or not use relative URLs (which makes it hard to develop locally or have a staging setup). I would suggest resolving relative URLs that have been picked up from the DOM relative to `location` (or whatever the page’s base path is), which is how relative URLs work in HTML in general.

**Comment by claviska** [comment]
We can definitely check for relative URLs and update them, probably with [`URL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL).

**Comment by LeaVerou** [comment]
> We can definitely check for relative URLs and update them, probably with [`URL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL).

No need to check, just pass it through the `URL()` constructor, if it’s absolute then it just remains unchanged.
