### ISSUE TITLE
[Tab Panel] `label` attribute that auto-generates the necessary `<wa-tab>` elements

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#249]
I hate to suggest this when we [_just_](https://github.com/shoelace-style/webawesome/pull/247) implemented auto-slotting for `<wa-tab>` but looking at even the "new" code, there's a fair bit of repetition:

```html
<wa-tab-group>
  <wa-tab panel="general">General</wa-tab>
  <wa-tab panel="custom">Custom</wa-tab>
  <wa-tab panel="advanced">Advanced</wa-tab>

  <wa-tab-panel name="general">This is the general tab panel.</wa-tab-panel>
  <wa-tab-panel name="custom">This is the custom tab panel.</wa-tab-panel>
  <wa-tab-panel name="advanced">This is the advanced tab panel.</wa-tab-panel>
</wa-tab-group>
```

Adding a new tab involves creating two elements in two separate places. While it’s useful to support slots for more complex use cases (inline formatting, badges, icons, i18n etc) in the vast majority of cases the tab name is just a string, so this seems like an example where the complex case gets in the way of the simple one.

What if we also supported a shortcut like:

```html
<wa-tab-group>
  <wa-tab-panel name="general" label="General">This is the general tab panel.</wa-tab-panel>
  <wa-tab-panel name="custom" label="Custom">This is the custom tab panel.</wa-tab-panel>
  <wa-tab-panel name="advanced" label="Advanced">This is the advanced tab panel.</wa-tab-panel>
</wa-tab-group>
```

that would generate the necessary `<wa-tab>` elements without the user having to do it manually. I think that provides a much nicer use case complexity to UI complexity curve, where you only use the heavyweight syntax when you need to go further, not because there's nothing easier.

_(In some ways this is similar to the shortcut I proposed for icons in #234 which makes me wonder if there’s a more general theme.)_

**Comment by claviska** [comment]
A label attribute doesn't support HTML content and requires the tab-panel to inject HTML into the tab-group OR the tab-group to parse panels and inject into itself 😕

**Comment by LeaVerou** [comment]
> A label attribute doesn't support HTML content

From the OP:
> While it’s useful to support slots for more complex use cases (inline formatting, badges, icons, i18n etc) in the vast majority of cases the tab name is just a string

I wasn't suggesting we drop `<wa-tab>`. This is a shortcut for the many cases where you don't need its power.

> and requires the tab-panel to inject HTML into the tab-group OR the tab-group to parse panels and inject into itself 😕

Are you saying it's poor DX for authors, difficult to implement, or an architecture wart? (My answer would be different depending on which one it is so I figured I'd check)

**Comment by claviska** [comment]
> Are you saying it's poor DX for authors, difficult to implement, or an architecture wart?

A bit of each, really. I get where you're coming from, but I'm not sold on the "multiple ways to do one thing" approach for most things, particularly when it feels unclean to implement (but implementation isn't my primary concern).

I'm a big fan of reducing friction and making things easier, so nothing is off the table here, but are there any existing patterns in the platform that work this way? Would people expect something like this to work? As a user, I _think_ I would feel like that's clunky, but it could be the purist in me coming out too.

**Comment by LeaVerou** [comment]
> I get where you're coming from, but I'm not sold on the "multiple ways to do one thing" approach for most things, particularly when it feels unclean to implement (but implementation isn't my primary concern).

Would it help if instead of "multiple ways of doing one thing" (which makes it sound arbitrary, like we couldn't decide what the best way was) you framed it as an application of the [rule of least power](https://www.w3.org/2001/tag/doc/leastPower.html), i.e. you use progressively more complex things as the complexity of your use case increases (I actually did [a whole talk on this exact thing](https://www.youtube.com/watch?v=g92XUzc1OHY) and it was very well received). Ideally you want the API to smoothly transition from one to the other, but oftentimes that’s not possible and you end up using different methods for the simple cases vs the complex cases. 

> I'm a big fan of reducing friction and making things easier, so nothing is off the table here, but are there any existing patterns in the platform that work this way? Would people expect something like this to work?

I think there is a lot of precedent **in WA itself**! For example:
- I counted 17 components that have a `label` attribute and 8 that have a `label` slot.
- 8 components have both a `help-text` attribute and a `help-text` slot

Also, conceptually there is no reason for `<wa-tab>` to be a sibling if you think about it. It's very much tied to the tab panel and has no meaning outside of it. Presumably the reason it's a sibling is because we want to slot it into the tab strip, which is separate.

WRT precedent in the platform, since native elements don't use slots it's hard to find the exact same thing, but some similar patterns are:
- `<option>`: When label == value, you can just specify it as element content. Otherwise, you can use either `value` or `label` or both.
- Many elements are auto-generated if not provided: `<tbody>`, `<html>`, `<body>`, `<head>`
- `<label>` does not need a `for` if the form element is within it

> As a user, I _think_ I would feel like that's clunky, but it could be the purist in me coming out too.

Again, I think this is about the framing. If you frame it as "here's two ways to do the same thing" with no rationale, it definitely feels clunky! If you frame it as "for most cases, you'd just use the `label` attribute. Some times you need HTML though, and then you use the `<wa-tab>` element and associate them via the `name` attribute" (I just realized you don't even need a `name` when you specify the tab on the panel since there’s nothing to associate).

**Comment by LeaVerou** [comment]
Actually, thinking about this some more, I don't think this is the right solution at all. I’m closing this and I'll file a new issue.
