### ISSUE TITLE
Consistent prefixing of WA CSS properties

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#258]
Currently, all custom properties in Applied CSS/themes are `--wa-` prefixed, but none of the [component-specific CSS properties](https://webawesome-git-next-font-awesome.vercel.app/docs/components/reference#all-css-custom-properties) are prefixed.

I don’t feel strongly about which way to go, only that these should be consistent.

Given @claviska's thoughts in #224, I assume prefixing is the way to go, but just to play devil's advocate for a bit: it could be argued that it could help adoption if our design tokens were not prefixed so that people can write extensions that use e.g. `--color-blue-50` which could be coming from WA, or anywhere else. We could then use `@layer` (or just `:where(:root)`) to deprioritize them in the cascade so that if the host page is setting them to anything else, that wins (though then we lose the contrast guarantee).

Anyhow, which way should we go here?

**Comment by claviska** [comment]
These are different beasts, though. Prefixed custom properties are global whereas unprefixed are scoped to the element. Conflating the two seems confusing. 😕

**Comment by LeaVerou** [comment]
Since custom properties inherit, it is entirely possible an author has properties with these names on their page that they did not necessarily plan to apply to these components.

**Comment by claviska** [comment]
They're defined on the host element, so they would need to intentionally do it or have an unreasonably high specificity for that to happen.

**Comment by LeaVerou** [comment]
Notes from today's meeting: it may be ok if the element-specific properties are unprefixed because we do reset them on the element, so only if they are specified on the element they get applied from the author side, so as @lindsaym-fa put it, "the element is the prefix". So I think it's fine to continue alongside the current path. To facilitate aggregation, we *could* define global properties for some of these, e.g. `--wa-avatar-size` (edit: this is now discussed in #536)
