### ISSUE TITLE
Support isolated code examples that are rendered in an `<iframe>`

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#270]
This is needed for #257 as we can't have `<wa-page>` demos that just live in a `<div>`, `<wa-page>` is intended for whole pages.

We could use a class name flag for this, e.g. `.isolated`.

Many but not all isolated code examples would also need zooming (e.g. without that all `<wa-page>` demos would render a mobile view!). We could do that with an attribute (e.g. `data-zoom="2"`) or a CSS property (`style="--zoom: 2"`).

The way I proposed handling this is:
- We use `<iframe srcdoc>` to render the example. That way we don't need to build a separate page.
- If zooming is needed, we render a larger iframe, and then use transforms to scale it down (and clipping)
- @claviska proposed also using `inert` on these to prevent them from trapping focus. I wonder if `tabindex="-1"` might be a better solution so that they can remain interactive.

**Comment by KonnorRogers** [comment]
Things to note when I did this while working on `<light-preview>` , if the `<iframe>` is meant to resize based on content, we need to add a ResizeObserver within the `<iframe>` and tell the host page about the resize to resize the code container. If not, we'll generally want a static `height` for the iframes.

The other thing is obviously the extra boilerplate around making sure to import the global stylesheet, and import the autoloader. I can't remember if there was any issues around content escaping for `srcdoc`, but being an attribute im sure they exist.

**Comment by LeaVerou** [comment]
Closed via #281
