### ISSUE TITLE
[Page] Support more units for `mobile-breakpoint`

### ISSUE THREAD

**Issue by lindsaym-fa** [shoelace-style/webawesome#299]
General consensus among that team is that we want to support other CSS units like `rem`, `em`, `ch`, etc. Unitless values should still be interpreted as `px`.

We also had a specific request for this [on Kickstarter](https://www.kickstarter.com/projects/fontawesome/web-awesome/posts/4271891):

> One thing I would like to see for the mobile breakpoint to not only support pixels, but also rem, em or whatever unit. I'm very used to (and biased towards) setting all widths, height, margins etc in rem units. There are many things to say about using pixels or other units, but just supporting pixels alone feels restricted to me.

**Comment by LeaVerou** [comment]
Fixed in https://github.com/shoelace-style/webawesome/pull/303
