### ISSUE TITLE
Opting out of Applied Styles

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#300]
@claviska was keen to do this as he was worried about conflicts. 

There are several considerations here and several ways to go about it.
 
Ideally this would mainly be used for for very specialized cases (e.g. you want to display some HTML with a completely different style e.g. for docs or whatnot). This means we need to make sure to pick specificity and cascade order very deliberately so that the styles are helpful, and don't get in the way when you don’t want them, without requiring the sledgehammer that is the opt-out.

## Reqs

In terms of the opt-out itself, ideally we want:
- A general opt-out that turns off all WA classless CSS (or should it also turn off utils?)
- A more specific opt-out that turns off WA classless CSS for specific elements
- In-betweens for certain groupings of elements (forms are a clear one that comes to mind)
- The opt-out must work on both the element itself, as well as an ancestor

## Implementation

In terms of implementation, we want to find a good balance between keeping our own CSS readable, and supporting a large number of use cases. We should especially try to minimize the amount of extra CSS **per rule** even if it adds more CSS per file or per group.

Meaning, **we definitely _don’t_ want to write every rule like this** unless we can generate it at build time:

```css
.wa-off {
	&, .wa-forms-off:not(&) {
		&, .wa-buttons-off:not(&) {
			:not(&, & *) {
				button& { /* native button styles */ }
			}
		}
	
		&, .wa-checkboxes-off:not(&) {
			:not(&, & *) {
				input[type=checkbox]& { /* native checkbox styles */ }
			}
		}
	}

	&, .wa-details-off:not(&) {
		:not(&, & *) {
			details& { /* native details styles */ }
		}
	}
}
```

I’ll have a think about how to do it better, and if I can't come up with a good way, we'd need to decide between doing a less powerful opt-out (e.g. only on an ancestor) or transforming the CSS at build time. But let's cross that bridge when we get to it.

**Comment by LeaVerou** [comment]
In the interest of time, let’s go with a simple `.wa-off` switch for now that can be applied on either an ancestor or individual elements) and as use cases emerge we can explore more narrowly scoped ones.

**Comment by LeaVerou** [comment]
Even with a single opt-out, [it gets pretty unwieldy](https://github.com/shoelace-style/webawesome/blob/next/src/styles/native/dialog.css#L17). So I’ve been thinking:

One nice way to deal with this is to add all our styles in a cascade layer, and then the opt-out becomes a matter of `all: revert-layer`. And given how simple it is to do that, we can have all the elaborate opt-outs that we originally envisioned.

And we don't even need to modify our styles at all, we can just use [`layer()` `@import`s](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) (yes, supported everywhere).

However! Adding all our styles in a layer means ALL (unlayered) author styles override them, even things like `* { padding: 0; margin: 0 }`. It could be argued that given this is a CSS reset, so why would you include ANOTHER reset? But shit happens.

That said, we could not use any layers in our own CSS, and just instruct people to import using `layer()` and have a note that if they face issues with conflicts, they can remove that, but the opt-out won’t work. 

Thoughts @claviska @lindsaym-fa ?

**Comment by claviska** [comment]
I'm aware of CSS layers, but I haven't explored them yet and I suspect most of our users haven't either. Whatever we ship, it needs to be easy to use or people will struggle with it.

If an opt out is too cumbersome, we can always remove it for _this week_ and revisit the concept. I don't want to add something hastily without being able to 1) properly understand it and 2) properly test it.

**Comment by claviska** [comment]
Also — this is designed to be an opinionated reset, so the primary opt out is to not use it. I'd be curious to learn from our users what they actually need to opt out of. We may realize they're perfectly OK with layering custom styles _on top of ours_ as opposed to opting specific elements out and styling said elements entirely from scratch.

**Comment by LeaVerou** [comment]
The opt-out wouldn’t require understanding of CSS layers. The only difference would be how you include the stylesheet. Currently, we tell people to copy this:

```html
<link rel="stylesheet" href="https://early.webawesome.com/webawesome@3.0.0-alpha.5/dist/styles/themes/applied.css" />
```

If we do this, we'll tell them to copy this instead:
```html
<style>@import url("https://early.webawesome.com/webawesome@3.0.0-alpha.5/dist/styles/themes/applied.css") layer(web-awesome); </style>
```

That’s it. The opt-out would be a class, just as originally designed, implemented like this rather than being coupled with every single selector:

```css
.wa-off,
.wa-off-deep * {
	all: revert-layer;
}
```

> Also — this is designed to be an opinionated reset, so the primary opt out is to not use it.

Indeed, the opt-out is not to remove these styles, it's primarily for cases where you want completely different styling for a section of the page and these styles would just get in the way.

**Comment by lindsaym-fa** [comment]
I'm down with this approach, especially because this:
> rather than being coupled with every single selector

...means we'll be much less error prone.

**Comment by LeaVerou** [comment]
Another advantage is that we can punt this entirely for now and keep it as a docs-only improvement 😁
