### ISSUE TITLE
Docs tables should link to documentation about how to use these things

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#313]
Things like slots, parts, custom states are esoteric for folks not used to web components. We have docs about how to use most of these, we need to 

- [ ] Add docs about custom states
- [ ] Link to these docs from each table

Linking could be either a little info icon next to the table header, or a link like "Read more: How to use parts?" at the end, or ideally both.

**Comment by claviska** [comment]
This seemed like a natural fit for #314 so I kicked it off with e973b59 and d09ea4a73a0923709f0b922ea2c54f22084d3e42.
