### ISSUE TITLE
wa-off example

### ISSUE THREAD

**Issue by kelseythejackson** [shoelace-style/webawesome#319]
On one of the opting out examples. The `wa-off` example on the blockquote doesn't seem to change anything.

![Image](https://github.com/user-attachments/assets/3b828c39-e01a-46bf-9c7a-2263acf77918)

@lindsaym-fa guessing you worked on this? Am I missing something

**Comment by LeaVerou** [comment]
We're tracking this in #300 — the opt-out is not done yet :)
