### ISSUE TITLE
Dropdowns in button groups have incorrect border radius

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#348]
![Image](https://github.com/user-attachments/assets/a41f8c43-db38-4246-ae90-d233f4f3b3a4)

**Comment by KonnorRogers** [comment]
I believe this was caused by the removal of the `button--last` / `button--first` classes, not sure how to resolve without adding those back.

**Comment by KonnorRogers** [comment]
Commit here:

https://github.com/shoelace-style/webawesome/commit/426a242d26c42dc48dc1ecf0199d2f42ae4dd6ae#diff-aa6a197cc512f5fab394bff2138de6e307a26c94a7f3eca42dce6d388a0f358cL400-L469

if we want to revert it back to having these styles until we have a more elegant solution?

**Comment by LeaVerou** [comment]
I'm really hoping we can find a better solution, these styles have no business living in button. Maybe let's leave this one last?
