### ISSUE TITLE
Checkbox (component) check is slightly off in Safari

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#350]
![Image](https://github.com/user-attachments/assets/9cb6d2ce-90cf-4abd-bd1b-05f6fcf79c58)

![Image](https://github.com/user-attachments/assets/809938bc-1b18-4d8d-b976-090a161452f0)

Seems fine in Chrome/Firefox.

**Comment by KonnorRogers** [comment]
https://github.com/user-attachments/assets/49475c6a-11ca-4caa-8255-96740cc2a2e5

I cant quite figure out whats up with this. Its related to zooming in / out in Safari. something about the SVG rendering seems to get jacked up as you zoom out more, but zooming in works fine 🤔
