### ISSUE TITLE
Color Picker z-index issue on firefox with code examples

### ISSUE THREAD

**Issue by KonnorRogers** [shoelace-style/webawesome#353]
https://github.com/user-attachments/assets/92a9e779-281f-4529-8136-4991ffc9f958

**Comment by claviska** [comment]
Is this the correct video? Look the same as #354

**Comment by KonnorRogers** [comment]
Yes it's correct. The first interaction is Safari behavior, second interaction is Firefox. I was just lazy and made it 1 video.

**Comment by KonnorRogers** [comment]
This is fixed for me 🤔
