### ISSUE TITLE
Safari closing behavior for color picker is erratic

### ISSUE THREAD

**Issue by KonnorRogers** [shoelace-style/webawesome#354]
https://github.com/user-attachments/assets/aa20cbda-2344-4ec7-b9a0-3e9228707af4

**Comment by LeaVerou** [comment]
Which version? Cannot reproduce in Safari 18.1

**Comment by KonnorRogers** [comment]
17.5

**Comment by KonnorRogers** [comment]
Hmmm...fixed for me now. Docker Desktop did decide to have a memory leak, dont know if that affected it.
