### ISSUE TITLE
Disabled range (component) doesn't have disabled styles in Safari

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#357]
Local link: http://localhost:4000/docs/components/range/#disabled

![Image](https://github.com/user-attachments/assets/f0bb3758-d8e6-41b0-bfbb-c957b9128db5)

Chrome/Firefox:

![Image](https://github.com/user-attachments/assets/13cc1ad7-1816-437d-b9f7-ce571736c9aa)

**Comment by lindsaym-fa** [comment]
Fixed with https://github.com/shoelace-style/webawesome/commit/431d23d420ce23e7e8dd357692693a19d0f7b797
