### ISSUE TITLE
Avatar examples in Safari have no spacing

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#359]
Safari

![Image](https://github.com/user-attachments/assets/2a30a267-f9e5-4645-abfb-a58e736cf5cb)

Chrome/Firefox:

![Image](https://github.com/user-attachments/assets/926b4d88-ddaa-4ecb-9e02-3c5118fe3bed)

**Comment by KonnorRogers** [comment]
This seems related to #352 , I can't consistently reproduce, but it seems to happen more than the "size" issue reported there.

**Comment by claviska** [comment]
This seems to be fixed now.
