### ISSUE TITLE
Resizing `<wa-textarea>` is janky

### ISSUE THREAD

**Issue by lindsaym-fa** [shoelace-style/webawesome#366]
Issue exists in all browsers and also the backers website. Wonder if this is a `<wa-code-demo>` issue?

Is the textarea a :party_parrot: or...?
https://github.com/user-attachments/assets/114d3c74-9b08-428d-8ccf-0ae39b44a74b

**Comment by KonnorRogers** [comment]
Not a `<wa-code-demo>` issue. Its present in plain text areas.

**Comment by LeaVerou** [comment]
Yeah I noticed this too, thanks for filing it! I would say it's low priority though: It's neither a regression nor very obvious.

**Comment by KonnorRogers** [comment]
it actually is a regression :/

it worked here in alpha.4

https://codepen.io/paramagicdev/pen/NPKjKwW?editors=1000

it basically boiled down to us not reflecting the "resize" property.
