### ISSUE TITLE
Can't expand the components section in the sidebar in Safari

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#368]
https://github.com/user-attachments/assets/2c4594ac-be5b-417d-a8f5-9df706b2c17e

**Comment by kelseythejackson** [comment]
It's happening on Chrome & Firefox too

**Comment by LeaVerou** [comment]
I cannot reproduce in Safari 18.1 🤔

**Comment by LeaVerou** [comment]
@KonnorRogers said this was fixed in https://github.com/shoelace-style/webawesome/commit/835326a2dbca14d981ca2aaa8abbc9da167fcf7a
