### ISSUE TITLE
Component section doesn't have any content when using `npm run start:alpha`

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#373]
https://github.com/user-attachments/assets/cc8cf1aa-c919-49d4-8b6d-8a5014590087

**Comment by LeaVerou** [comment]
Cannot repro on Safari 18.1 (no patch version)

**Comment by claviska** [comment]
Seems to occur in all browsers, but only when using `npm run start:alpha`. Looks like there's alpha logic that might be causing it.

**Comment by claviska** [comment]
This was a check for the wrong value. References to `component.data.isAlpha` should be `component.data.noAlpha`, which is set in the component's markdown file.

```
{% if not component.data.parent and not (isAlpha and component.data.isAlpha) %}
```

Became:

```
{% if not component.data.parent and not (isAlpha and component.data.noAlpha) %}
```

And it's working as intended now.
