### ISSUE TITLE
Dropdowns don't respect button `pill` attribute

### ISSUE THREAD

**Issue by lindsaym-fa** [shoelace-style/webawesome#378]
Following https://github.com/shoelace-style/webawesome/commit/c0012f5b94dce6d76f53a9c33f66f2b2b7fe9c87, buttons within dropdowns no longer support the `pill` attribute.

e.g., in our docs header —

Current:
<img width="422" alt="Image" src="https://github.com/user-attachments/assets/51755742-fa58-4c98-a4ff-0c145505a990" />

Backers:
<img width="422" alt="Image" src="https://github.com/user-attachments/assets/a6c4f06d-130d-45ff-9518-4845749e5631" />

(I'm not mad about these particular ones being more square,  but we did regress re: supported attributes.)

**Comment by LeaVerou** [comment]
Gah, it's caused by the fix in #348 . On it
