### ISSUE TITLE
Buttons within vertical button groups don't match width

### ISSUE THREAD

**Issue by lindsaym-fa** [shoelace-style/webawesome#379]
See http://localhost:4000/docs/components/button-group/#vertical-button-groups

<img width="748" alt="Image" src="https://github.com/user-attachments/assets/a2c23ab7-664d-4e67-9606-2226633c4364" />

**Comment by LeaVerou** [comment]
This was added by @claviska's fix to the alignment issue where he added `align-items: center` to button groups. I'm about to push a fix that doesn't require this.
