### ISSUE TITLE
Missing Padding on earlier version of Safari

### ISSUE THREAD

**Issue by kelseythejackson** [shoelace-style/webawesome#382]
### Describe the bug
In safari Version 17.5 (19618.2.12.11.6) we are missing padding in our button groups component

### Demo

https://github.com/user-attachments/assets/264fe67b-7056-40bb-a661-1b492b68086a

### Screenshots
If applicable, add screenshots to help explain the bug.

### Browser / OS
 - OS: Mac
 - Browser: Safari Version 17.5
 - Browser version: 17.5 (19618.2.12.11.6) 

### Additional information
Provide any additional information about the bug here.

**Comment by LeaVerou** [comment]
This was caused by a typo and has since been fixed
