### ISSUE TITLE
Rename `{name}.component.ts` to `{name}.ts`

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#70]
We need to worry about scoped custom elements (e.g. custom tags) any time soon, so it would be nice to eliminate the extra definition files by re-combining them with the source files. This will help reduce HTTP requests for every component.

**Comment by claviska** [comment]
Completed in the 11ty3 branch.

**Comment by RoXuS** [comment]
@claviska, so now what is the good way to import the component without register it inside the global registry?

**Comment by claviska** [comment]
This was never supported, not even in Shoelace. Splitting the files was prep work for that, but it it causes extra HTTP requests for no immediate benefit so we reverted to simplify things.

When [Scoped Custom Element Registries](https://wicg.github.io/webcomponents/proposals/Scoped-Custom-Element-Registries.html) are well-supported, we'll likely begin work to make that possible.

**Comment by RoXuS** [comment]
Thx. You already have a "big" build process, so we can eventually add a specific build step which produce components without the custom element decorator then expose these build under a specific esm export? There won't add any extra http request and then we will be able to get the components without registering.

If I do a PR, will you review it?

**Comment by claviska** [comment]
Sorry, there's more to it than just splitting the files, and we're not focused on this at all at the moment.
