### ISSUE TITLE
Improve documentation for <wa-page>

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#79]
- [ ] Review content to make sure it makes sense from a user's perspective
- [ ] Replace anatomy image with the attached SVG
- [ ] Suggest any improvements to order, content, etc.

![Image](https://github.com/shoelace-style/webawesome/assets/55639/6e4ec335-eccb-4674-a9e1-37d7bb2fd51e)

**Comment by LeaVerou** [comment]
@KonnorRogers has some demos here that we could integrate: https://webawesome-git-konnorrogers-layouts-font-awesome.vercel.app/layouts/index.html

**Comment by LeaVerou** [comment]
I'm inclined to close this, we can open separate issues for what remains.
