### ISSUE TITLE
PRO: date picker component

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#85]
The infamous date picker.

Discussion: https://github.com/shoelace-style/shoelace/discussions/1653

Prior art:
- https://dia-date-picker.com/date-picker.html#usage
- https://duetds.github.io/date-picker/

**Comment by claviska** [comment]
duplicate of #16

**Comment by LeaVerou** [comment]
(Reopened so I could close as "not planned" in the hopes it would move it out of "Done" but nope; sorry for the noise!)
