### ISSUE TITLE
PRO: combobox component

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#87]
The even more infamous combobox component.

Discussion: https://github.com/shoelace-style/shoelace/discussions/1648

Prior art:
- https://www.duetds.com/components/combobox/
- https://explore.fast.design/components/fast-combobox

**Comment by claviska** [comment]
Question: should `<wa-select>` and `<wa-combobox>` be use _one_ component? 🤔

**Comment by KonnorRogers** [comment]
@claviska My vote is for yes.

Since it's essentially:

```
<wa-combobox select-only>
```

It's just a variation of a combobox.

**Comment by KonnorRogers** [comment]
Additional prior art:

https://sarahmhigley.com/writing/select-your-poison/

**Comment by claviska** [comment]
duplicate of #15
